{{- if and (not .Values.secrets.existingSecret) .Values.secrets.inline }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vllm-orchestrator.fullname" . }}-secrets
  labels: {{- include "vllm-orchestrator.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secrets.inline }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
